name: Build (Windows)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload built app bundle
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: src-tauri/target/release/bundle/
